"use client";
import {motion} from "framer-motion";
import {Activity,BadgeIndianRupee,ChefHat,ChevronRight,LayoutDashboard,PackageCheck,Search,Settings,ShoppingBag,Store,Users} from "lucide-react";
import {AnimatedCard,Counter,FloatingOrb,Stagger,fadeUp} from "@/components/motion-ui";

const nav=[["Dashboard",LayoutDashboard],["Orders",ShoppingBag],["Customers",Users],["Partners",Store],["Menu & Products",ChefHat],["Payments",BadgeIndianRupee],["Reports",Activity],["Settings",Settings]] as const;
const stats=[["Total Orders",1284,"+12.4%"],["Revenue",846200,"+8.1%"],["Customers",3920,"+18.6%"],["Active Partners",186,"+6.8%"]];
const orders=[["ALN-26041","Riya Sharma","Green Bowl Kitchen","₹458","Preparing"],["ALN-26040","Aman Patel","Spice Route","₹729","Confirmed"],["ALN-26039","Neha Jain","Local Tandoor","₹1,120","Delivered"],["ALN-26038","Kabir Khan","Green Bowl Kitchen","₹349","Out for delivery"]];

export default function CRM(){
 return <main className="allino-surface-dark grid min-h-screen text-white lg:grid-cols-[250px_1fr]">
  <aside className="hidden border-r border-white/5 bg-[#081913] p-5 lg:block"><motion.div initial={{opacity:0,x:-15}} animate={{opacity:1,x:0}} className="mb-10 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-allino-gold text-allino-ink"><ChefHat/></span><div><b>ALLINO CRM</b><p className="text-xs text-white/40">Operations OS</p></div></motion.div><motion.nav initial="hidden" animate="show" variants={{show:{transition:{staggerChildren:.06}}}} className="space-y-1">{nav.map(([name,Icon],i)=><motion.button variants={fadeUp} key={name} className={"group flex w-full items-center justify-between rounded-xl px-3 py-3 text-left text-sm font-semibold transition "+(i===0?"bg-allino-gold text-allino-ink":"text-white/60 hover:bg-white/5 hover:text-white")}><span className="flex items-center gap-3"><Icon size={17}/>{name}</span><ChevronRight size={15} className="opacity-0 transition group-hover:opacity-100"/></motion.button>)}</motion.nav></aside>

  <section className="grid-bg relative min-w-0 overflow-hidden p-4 md:p-8"><FloatingOrb className="absolute right-10 top-10 h-72 w-72 rounded-full bg-allino-lime/10 blur-[90px]"/><FloatingOrb delay={2} className="absolute bottom-10 left-20 h-72 w-72 rounded-full bg-allino-gold/10 blur-[100px]"/>
   <div className="relative z-10 mx-auto max-w-[1500px]">
    <motion.header initial={{opacity:0,y:-12}} animate={{opacity:1,y:0}} transition={{type:"spring",stiffness:110,damping:20}} className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><p className="text-sm text-white/40">Sunday, 04 October</p><h1 className="mt-1 text-3xl font-black tracking-tight">Operations Dashboard</h1></div><div className="dark-glass flex items-center gap-3 rounded-xl px-4 py-3 text-sm text-white/50"><Search size={17}/><span>Search orders, customers, partners…</span></div></motion.header>

    <Stagger className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,delta])=><AnimatedCard key={label} className="dark-glass rounded-2xl p-5 shadow-glow"><div className="flex justify-between"><span className="text-sm text-white/50">{label}</span><span className="rounded-full bg-allino-lime/10 px-2 py-1 text-xs font-bold text-allino-lime">{delta}</span></div><div className="mt-5 text-3xl font-black">{label==="Revenue"?"₹":""}<Counter value={Number(value)}/></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/5"><motion.div initial={{width:0}} whileInView={{width:"72%"}} viewport={{once:true}} transition={{duration:.8}} className="h-full rounded-full bg-allino-gold"/></div></AnimatedCard>)}</Stagger>

    <div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]">
      <motion.div initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} transition={{type:"spring",stiffness:105,damping:20,delay:.12}} className="dark-glass overflow-hidden rounded-2xl"><div className="flex items-center justify-between border-b border-white/5 p-5"><div><h2 className="font-black">Recent Orders</h2><p className="mt-1 text-xs text-white/40">Live operational queue</p></div><button className="text-xs font-bold text-allino-gold">View all</button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs uppercase tracking-wider text-white/30"><tr>{["Order","Customer","Kitchen","Amount","Status"].map(x=><th key={x} className="px-5 py-4 font-semibold">{x}</th>)}</tr></thead><tbody>{orders.map((r,idx)=><motion.tr initial={{opacity:0,x:-8}} animate={{opacity:1,x:0}} transition={{delay:.32+idx*.06}} key={r[0]} className="crm-row border-t border-white/5 text-white/70">{r.map((c,i)=><td key={i} className="px-5 py-4">{i===4?<span className={"rounded-full bg-allino-lime/10 px-2.5 py-1 text-xs font-bold text-allino-lime "+(c==="Preparing"?"status-live":"")}>{c}</span>:c}</td>)}</motion.tr>)}</tbody></table></div></motion.div>
      <div className="space-y-6"><motion.div initial={{opacity:0,scale:.96}} animate={{opacity:1,scale:1}} transition={{type:"spring",stiffness:105,damping:20,delay:.16}} className="dark-glass rounded-2xl p-5"><h2 className="font-black">Order Flow</h2><p className="mt-1 text-xs text-white/40">Current operational distribution</p><div className="mt-6 space-y-4">{[["Placed",86],["Preparing",63],["Ready",42],["Out for delivery",71],["Delivered",94]].map(([x,v])=><div key={x}><div className="mb-1 flex justify-between text-xs"><span className="text-white/55">{x}</span><span className="font-bold">{v}%</span></div><div className="h-2 rounded-full bg-white/5"><motion.div initial={{scaleX:0}} animate={{scaleX:Number(v)/100}} transition={{delay:.45,duration:.65}} style={{transformOrigin:"left"}} className="h-full rounded-full bg-gradient-to-r from-allino-lime to-allino-gold"/></div></div>)}</div></motion.div>
      <motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{type:"spring",stiffness:105,damping:20,delay:.2}} className="rounded-2xl bg-gradient-to-br from-allino-green to-[#102f24] p-5"><p className="text-xs font-bold uppercase tracking-[.18em] text-allino-gold">Partner pipeline</p><h3 className="mt-3 text-2xl font-black">23 kitchens onboarding</h3><p className="mt-2 text-sm text-white/50">KYC → Kitchen → Menu → Verification → Approval</p></motion.div></div>
    </div>
   </div>
  </section>
 </main>
}
